substitutions:
  sensor_gpio_left: GPIO10
  sensor_gpio_right: GPIO20

packages:
  left_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: Left
      sensor_id: left
      sensor_gpio: ${sensor_gpio_left}

  right_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: Right
      sensor_id: right
      sensor_gpio: ${sensor_gpio_right}

sensor:
  - platform: wifi_signal   # Reports the WiFi signal strength in dB
    name: WiFi Signal dB
    id: wifi_signal_db
    update_interval: 60s

  - platform: copy          # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: WiFi Signal Percent
    id: wifi_signal_percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: '%'
    entity_category: diagnostic
    device_class: ""

  - platform: uptime
    type: seconds
    id: bed_presence_uptime
    name: Uptime

binary_sensor:
  - platform: template
    name: Bed Occupied Both (Fast)
    id: bed_occupied_both_fast
    device_class: occupancy
    icon: mdi:bunk-bed
    disabled_by_default: true
    lambda: return id(bed_occupied_left_fast).state && id(bed_occupied_right_fast).state;

  - platform: template
    name: Bed Occupied Either (Fast)
    id: bed_occupied_either_fast
    device_class: occupancy
    icon: mdi:bunk-bed
    disabled_by_default: true
    lambda: return id(bed_occupied_left_fast).state || id(bed_occupied_right_fast).state;

  - platform: template
    name: Bed Occupied Both
    id: bed_occupied_both
    device_class: occupancy
    icon: mdi:bunk-bed
    lambda: return id(bed_occupied_left).state && id(bed_occupied_right).state;

  - platform: template
    name: Bed Occupied Either
    id: bed_occupied_either
    device_class: occupancy
    icon: mdi:bunk-bed
    lambda: return id(bed_occupied_left).state || id(bed_occupied_right).state;

  - platform: status
    id: bed_presence_status
    name: Status

button:
  - platform: restart
    name: Restart
    id: btn_restart
    entity_category: diagnostic

switch:
  - platform: template
    name: Full Range
    id: full_range
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    icon: mdi:arrow-expand
