packages:
  left_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: Left
      sensor_id: left
      sensor_gpio: GPIO10

  right_bed_sensor: !include
    file: sensor.yaml
    vars:
      sensor_name: Right
      sensor_id: right
      sensor_gpio: GPIO20

sensor:
- platform: wifi_signal # Reports the WiFi signal strength in dB
  name: WiFi Signal dB
  id: wifi_signal_db
  update_interval: 60s

- platform: copy # Reports the WiFi signal strength in %
  source_id: wifi_signal_db
  name: "WiFi Signal Percent"
  id: wifi_signal_percent
  filters:
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
  unit_of_measurement: "%"
  entity_category: "diagnostic"
  device_class: ""

binary_sensor:
- platform: template
  name: Bed Occupied Both (Fast)
  id: bed_occupied_both_fast
  device_class: occupancy
  icon: mdi:bed
  disabled_by_default: true
  lambda: return id(bed_occupied_left_fast).state && id(bed_occupied_right_fast).state;

- platform: template
  name: Bed Occupied Either (Fast)
  id: bed_occupied_either_fast
  device_class: occupancy
  icon: mdi:bed
  disabled_by_default: true
  lambda: return id(bed_occupied_left_fast).state || id(bed_occupied_right_fast).state;

- platform: template
  name: Bed Occupied Both
  id: bed_occupied_both
  device_class: occupancy
  icon: mdi:bed
  lambda: return id(bed_occupied_left).state && id(bed_occupied_right).state;

- platform: template
  name: Bed Occupied Either
  id: bed_occupied_either
  device_class: occupancy
  icon: mdi:bed
  lambda: return id(bed_occupied_left).state || id(bed_occupied_right).state;

button:
- platform: restart
  name: Restart
  id: btn_restart
  entity_category: "diagnostic"
- platform: safe_mode
  id: btn_safe_mode
  name: Safe Mode Boot
  entity_category: "diagnostic"
- platform: factory_reset
  id: btn_factory_reset
  name: Factory Reset
  entity_category: "diagnostic"
