substitutions:
  name: bed-presence
  friendly_name: Bed Presence

  # Calibrate Trigger Percentile
  # This controls how the trigger threshold is set during calibration. During calibration, the unoccupied and occupied
  # pressure values are determined. This is the percentage of the difference between those values required to trigger
  # the "occupied" state.
  #     - 0.75   Less sensitive, requires 75% of the occupied pressure to trigger
  #     - 0.50   Set trigger exactly in the middle of unoccupied and occupied pressures (Default)
  #     - 0.25   More sensitive, likely to be triggered by partner
  trigger_percentile: '0.90'

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ElevatedSensors.BedPresenceMk1
    version: "2024.7.1"
    release_summary: ""
    release_url: ""

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Allow Import
dashboard_import:
  package_import_url: github://ElevatedSensors/sensor-configs/bed-presence-mk1.yaml@main
  import_full_config: true

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

# Enable esphome OTA updates
ota:
  platform: esphome

## Managed Updates from Elevated Sensors
#ota:
#- platform: http_request
#
#http_request:
#  verify_ssl: false
#
#update:
#  - platform: http_request
#    name: Firmware Update
#    source: https://dev.elevatedsensors.com/sensor-configs-/manifest.json
#    update_interval: 6h

################################################################################
packages:
  remote_package:
    url: https://github.com/ElevatedSensors/sensor-configs
    ref: main
    files: ['bed-presence-mk1/base.yaml']
    refresh: 1s
