substitutions:
  name: "bed-presence"
  friendly_name: Bed Presence
  
  # Auto Calibrate
  # What happens to the auto calibration switch when the device power cycles?
  #     - RESTORE_DEFAULT_ON - Attempt to restore previous state, but enable auto calibration if not possible to restore (Default)
  #     - RESTORE_DEFAULT_OFF - Attempt to restore previous state, but disable auto calibration if not possible to restore
  #     - ALWAYS_ON - Always enable auto calibration
  #     - ALWAYS_OFF - Always disable auto calibration
  calibration_auto_restore: RESTORE_DEFAULT_ON

  # Auto Calibrate Trigger Percentile
  # This controls how the trigger threshold is set when auto calibration is enabled. This is the percentage of the
  # observed pressure that is required to register the bed as occupied. During auto calibration, the system stores the
  # minimum and maximum pressures that it sees and used those values in combination with the trigger_percentile to 
  # calculate the trigger threshold.
  #     - 0.75   Require 75% of the maximum measured pressure to trigger (Default)
  #     - 0.50   Set trigger exactly in the middle of minimum and maximum measured pressures
  #     - 0.20   More sensitive, might trigger with light items placed on bed
  trigger_percentile: "0.75"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ElevatedSensors.BedPresence
    version: '0.1'

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Allow updates from ElevatedSensors Github
dashboard_import:
  package_import_url: github://ElevatedSensors/sensor-configs/bed-presence-mk1.yaml
  import_full_config: true

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

################################################################################
# Sensor Configs

binary_sensor:
  - platform: template
    name: "Bed Occupied"
    id: bed_occupied
    device_class: occupancy
    icon: mdi:bed # make switch between bed and bed-empty
    lambda: |-
      if (id(bed_sensor).state > id(val_trigger).state) {
        return true;
      } else {
        return false;
      }

sensor:
  - platform: pulse_counter
    pin: GPIO3
    name: Pressure (Current)
    id: bed_sensor
    update_interval: 0.5s
    unit_of_measurement: "%"
    icon: mdi:gauge
    filters: 
      - sliding_window_moving_average: 
          window_size: 10   # average over 10 samples/5 seconds
          send_every: 1     # send every 0.5s
      - lambda: return x*100/7000/60;  # scale 0->7000Hz to 0->100%
      - clamp:
          min_value: 0
          max_value: 100
      - or: 
          - delta: 0.1         # only send if sensor change +/- by 0.1
          - throttle: 60s      # but still update every minute
      #- lambda: return x/60; # frequency
    on_value: 
      then:
        # Update min/max states
        - lambda: |-
            if (x > id(val_max).state) {
                auto call = id(val_max).make_call();
                call.set_value(x);
                call.perform();
            }
            if (x < id(val_min).state) {
                auto call = id(val_min).make_call();
                call.set_value(x);
                call.perform();
            }
  - platform: template
    name: Pressure (Min)
    id: val_min_status
    icon: mdi:gauge-empty
    unit_of_measurement: "%"
  - platform: template
    name: Pressure (Max)
    id: val_max_status
    icon: mdi:gauge-full
    unit_of_measurement: "%"

number:
  - platform: template
    id: val_min
    optimistic: True
    restore_value: True
    initial_value: 100
    min_value: 0
    max_value: 100
    step: 0.01
    on_value: 
      then:
        # Update status and trigger (if auto calibrating)
        - lambda: |-
            id(val_min_status).publish_state(x);
            if (id(calibrate_auto).state) {
              id(update_trigger)->execute();
            }
  - platform: template
    id: val_max
    optimistic: True
    restore_value: True
    initial_value: 0
    min_value: 0
    max_value: 100
    step: 0.01
    on_value: 
      then:
        # Update status and trigger (if auto calibrating)
        - lambda: |-
            id(val_max_status).publish_state(x);
            if (id(calibrate_auto).state) {
              id(update_trigger)->execute();
            }
  - platform: template
    name: Pressure (Trigger)
    id: val_trigger
    optimistic: True
    restore_value: True
    initial_value: 50
    min_value: 0
    max_value: 100
    step: 0.01
    icon: mdi:gauge
    unit_of_measurement: "%"
  
button:
  - platform: template
    name: Calibration (Reset)
    icon: mdi:sync
    on_press: 
      then:
        - number.set:
            id: val_min
            value: 100
        - number.set:
            id: val_max
            value: 0
        - number.set: 
            id: val_trigger
            value: 50
  
switch:
  - platform: template
    name: Calibration (Auto)
    id: calibrate_auto
    optimistic: True
    icon: mdi:auto-fix
    restore_mode: ${calibration_auto_restore}
  
script:
  - id: update_trigger
    mode: queued
    then:
      - lambda: |-  # Set val_trigger to x% of difference between min/max
          float min_pressure = id(val_min).state;
          float max_pressure = id(val_max).state;
          if (min_pressure <= max_pressure) {
              auto call = id(val_trigger).make_call();
              call.set_value(min_pressure + ((max_pressure - min_pressure) * float(${trigger_percentile})));
              call.perform();
          }
