name: Hubitat Bundles

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'integrations/hubitat/**'
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    name: Bundle
    steps:
      - uses: actions/checkout@v4

      - name: Build bpmk1 bundle
        run:  |
          mkdir bed-presence-mk1-bundle
          cp integrations/hubitat/bundles/bed-presence-mk1.txt bed-presence-mk1-bundle/install.txt
          cp integrations/hubitat/bundles/bed-presence-mk1.txt bed-presence-mk1-bundle/update.txt
          cp integrations/hubitat/drivers/bed-presence-mk1.groovy bed-presence-mk1-bundle/elevated_sensors.BedPresenceMk1.groovy
          wget -O bed-presence-mk1-bundle/esphome.espHomeApiHelper.groovy https://raw.githubusercontent.com/ElevatedSensors/hubitat-espHomeApiHelper/refs/heads/main/ESPHome/ESPHome-API-Library.groovy

      - name: Zip bpmk1
        uses: actions/upload-artifact@v4
        with:
          name: bed-presence-mk1-hubitat-bundle
          path: bed-presence-mk1-bundle/
